repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 87928e6d6761a4a6d22250e1fee5601b3998086e # 26.5.1
    hooks:
      - id: black
        language_version: python3.14
        args: [--line-length=120]

  - repo: https://github.com/pycqa/flake8
    rev: c48217e1fc006c2dddd14df54e83b67da15de5cd # 7.3.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--extend-ignore=E203,W503,E501"]

  - repo: https://github.com/pycqa/isort
    rev: 131f4adcd5582bfc53928ab0d740eceb8b506b6c # 9.0.1
    hooks:
      - id: isort
        args: [--profile=black, --line-length=120]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a6564f5d57444e123433a5c9af733e3975c77229 # v0.11.0.1-1
    hooks:
      - id: shellcheck
        args:
          - "-f"
          - "gcc"
          - "-e"
          - "SC1090,SC1091,SC2015,SC2034,SC2059,SC2317"
        files: \.sh$
